### ISSUE TITLE
Retore textual todos?

### ISSUE THREAD

**Issue by kerim** [nmartin84/logseq-flow#13]
The latest version of flow replaces TODO, NOW, DONE, etc. with colors. This is a major usability issue for me, how can I regress this? To be honest, I was never happy with the minimalism of just one letter, but that at least was manageable. Ideally I'd prefer to have the full text, like in the dev theme.

**Comment by nmartin84** [comment]
Hey @kerim - you can apply the following to your custom.css and it'll restore the original format. Also I should have customizable options showing up underneath the Settings panel here soon, where you can adjust things like this on the fly. 
```css
.block-marker.TODO, .block-marker.DOING, .block-marker.NOW, .block-marker.wait, .block-marker.waiting, .block-marker.LATER {
    font-size: 16px;
}
.block-marker.TODO:before, .block-marker.DOING:before, .block-marker.NOW:before, .block-marker.WAIT:before, .block-marker.waiting:before, .block-marker.LATER:before {
    font-size: 0px;
    font-weight: 700;
    color: var(--ls-primary-text-color);
    opacity: 0.7;
  padding-right: 0px;
}
```
