### ISSUE TITLE
query table width problem

### ISSUE THREAD

**Issue by henices** [nmartin84/logseq-flow#39]
version： 0.6.5

Logseq default theme：

![image](https://user-images.githubusercontent.com/929715/218689339-169254ad-3afb-41e4-b8fd-bfde400e9842.png)

Logseq Flow theme：

![image](https://user-images.githubusercontent.com/929715/218689593-9fbabad0-a814-4b9c-9831-06e33f66c938.png)

**Comment by nmartin84** [comment]
Thanks @henices - i'll post here after I have pushed a fix for this, should be later tonight or tomorrow.

**Comment by henices** [comment]
> Thanks @henices - i'll post here after I have pushed a fix for this, should be later tonight or tomorrow.

Thanks @nmartin84,  I like logseq flow theme very much, It's amazing.

**Comment by nmartin84** [comment]
@henices - glad you are enjoying it. A new version has been pushed which includes the fix for table width.

**Comment by henices** [comment]
Hi @nmartin84,  after modifing markdown.css, everything works well.

```css
table {                                                                                             
    border-radius: 4px;                                                                             
}
```
